apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.mysql
  version: v1
  metadata:
  - name: connectionString
    value: "root:password@tcp(mysql:3306)/users_db"
